jobs:
- job: tryThings
  displayName: TryAdminStuff
  pool:
    name: dotnet-external-temp-vs2017
  steps:
  - script: "REG QUERY HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System"
