jobs:
- job: verifyCerts
  displayName: VerifyCertsWork
  pool:
    name: dotnet-internal-temp-staging
  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'filePath' # Optional. Options: filePath, inline
      filePath: 'verifycertswork.ps1'
      #arguments: # Optional
      #script: '# Write your powershell commands here.' # Required when targetType == Inline
      #errorActionPreference: 'stop' # Optional. Options: stop, continue, silentlyContinue
      #failOnStderr: false # Optional
      #ignoreLASTEXITCODE: false # Optional
      #pwsh: false # Optional
      #workingDirectory: # Optional

