jobs:
- job: tryThings
  displayName: TryAdminStuff
  pool:
    name: dotnet-external-temp-vs2017
  steps:
  - powershell: Get-Item -Path Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System; start-sleep -seconds 60

