jobs:
- job: getVSversion
  displayName: VSWhere
  pool:
    name: dotnet-external-temp-staging
  steps:
  - powershell: C:\"Program Files (x86)"\"Microsoft Visual Studio"\Installer\vswhere -prerelease

