jobs:
- job: verifyCerts
  displayName: VerifyCertsWork
  pool:
    name: dotnet-internal-temp
  steps:
  - powershell: "C:\'Program Files (x86)'\'Microsoft Visual Studio'\Installer\vswhere.exe -all -prerelease"

